services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nytris\SymfonyPlugin\Shift\:
        resource: '../../../'
        exclude:
            - '../../../bootstrap.php'
            - '../../../Plugin.php'

    Asmblah\PhpCodeShift\Shift: ~
    Asmblah\PhpCodeShift\ShiftInterface: '@Asmblah\PhpCodeShift\Shift'
