services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Nytris\SymfonyPlugin\Shift\Cache\CacheClearer: ~

    Nytris\SymfonyPlugin\Shift\Cache\CacheWarmer: ~

    Asmblah\PhpCodeShift\Shift: ~
    Asmblah\PhpCodeShift\ShiftInterface: '@Asmblah\PhpCodeShift\Shift'
